service:
  name: common-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  memorySize: 128

custom:
  customDomain:
    domainName: api.dev.googit.co
    stage: dev
    basePath: common
    certificateName: "*.dev.googit.co"
    createRoute53Record: true

functions:
  sendToSlackRoom:
    handler: function/slack/index.labs
    events:
      - http:
          method: post
          path: send-to-channel-labs
