service:
  name: common-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  memorySize: 128

functions:
  sendToSlackRoom:
    handler: function/slack/index.labs
    events:
      - http:
          method: post
          path: send-to-channel-labs
